allowBuilds:
  '@clerk/shared': set this to true or false
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  sharp: set this to true or false
  stream-chat: set this to true or false
