/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitDemonRouteImport } from './routes/submit-demon'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AssessmentBoardRouteImport } from './routes/assessment-board'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiWarroomChatRouteImport } from './routes/api.warroom-chat'
import { Route as ApiSubmitAssessmentRouteImport } from './routes/api.submit-assessment'
import { Route as ApiResourcesDebugRouteImport } from './routes/api.resources-debug'
import { Route as ApiResourcesRouteImport } from './routes/api.resources'
import { Route as ApiResourceDownloadRouteImport } from './routes/api.resource-download'
import { Route as ApiMnWebhookRouteImport } from './routes/api.mn-webhook'
import { Route as ApiGenerateSummaryRouteImport } from './routes/api.generate-summary'
import { Route as ApiDemonsRouteImport } from './routes/api.demons'
import { Route as ApiAssessmentBoardRouteImport } from './routes/api.assessment-board'

const SubmitDemonRoute = SubmitDemonRouteImport.update({
  id: '/submit-demon',
  path: '/submit-demon',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBoardRoute = AssessmentBoardRouteImport.update({
  id: '/assessment-board',
  path: '/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarroomChatRoute = ApiWarroomChatRouteImport.update({
  id: '/api/warroom-chat',
  path: '/api/warroom-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitAssessmentRoute = ApiSubmitAssessmentRouteImport.update({
  id: '/api/submit-assessment',
  path: '/api/submit-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesDebugRoute = ApiResourcesDebugRouteImport.update({
  id: '/api/resources-debug',
  path: '/api/resources-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceDownloadRoute = ApiResourceDownloadRouteImport.update({
  id: '/api/resource-download',
  path: '/api/resource-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMnWebhookRoute = ApiMnWebhookRouteImport.update({
  id: '/api/mn-webhook',
  path: '/api/mn-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSummaryRoute = ApiGenerateSummaryRouteImport.update({
  id: '/api/generate-summary',
  path: '/api/generate-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemonsRoute = ApiDemonsRouteImport.update({
  id: '/api/demons',
  path: '/api/demons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentBoardRoute = ApiAssessmentBoardRouteImport.update({
  id: '/api/assessment-board',
  path: '/api/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/resources': typeof ResourcesRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/mn-webhook': typeof ApiMnWebhookRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/resources': typeof ResourcesRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/mn-webhook': typeof ApiMnWebhookRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/resources': typeof ResourcesRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/mn-webhook': typeof ApiMnWebhookRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/assessment-board'
    | '/resources'
    | '/submit-demon'
    | '/api/assessment-board'
    | '/api/demons'
    | '/api/generate-summary'
    | '/api/mn-webhook'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/submit-assessment'
    | '/api/warroom-chat'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/assessment-board'
    | '/resources'
    | '/submit-demon'
    | '/api/assessment-board'
    | '/api/demons'
    | '/api/generate-summary'
    | '/api/mn-webhook'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/submit-assessment'
    | '/api/warroom-chat'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/assessment-board'
    | '/resources'
    | '/submit-demon'
    | '/api/assessment-board'
    | '/api/demons'
    | '/api/generate-summary'
    | '/api/mn-webhook'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/submit-assessment'
    | '/api/warroom-chat'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  AssessmentBoardRoute: typeof AssessmentBoardRoute
  ResourcesRoute: typeof ResourcesRoute
  SubmitDemonRoute: typeof SubmitDemonRoute
  ApiAssessmentBoardRoute: typeof ApiAssessmentBoardRoute
  ApiDemonsRoute: typeof ApiDemonsRoute
  ApiGenerateSummaryRoute: typeof ApiGenerateSummaryRoute
  ApiMnWebhookRoute: typeof ApiMnWebhookRoute
  ApiResourceDownloadRoute: typeof ApiResourceDownloadRoute
  ApiResourcesRoute: typeof ApiResourcesRoute
  ApiResourcesDebugRoute: typeof ApiResourcesDebugRoute
  ApiSubmitAssessmentRoute: typeof ApiSubmitAssessmentRoute
  ApiWarroomChatRoute: typeof ApiWarroomChatRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-demon': {
      id: '/submit-demon'
      path: '/submit-demon'
      fullPath: '/submit-demon'
      preLoaderRoute: typeof SubmitDemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment-board': {
      id: '/assessment-board'
      path: '/assessment-board'
      fullPath: '/assessment-board'
      preLoaderRoute: typeof AssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warroom-chat': {
      id: '/api/warroom-chat'
      path: '/api/warroom-chat'
      fullPath: '/api/warroom-chat'
      preLoaderRoute: typeof ApiWarroomChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-assessment': {
      id: '/api/submit-assessment'
      path: '/api/submit-assessment'
      fullPath: '/api/submit-assessment'
      preLoaderRoute: typeof ApiSubmitAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources-debug': {
      id: '/api/resources-debug'
      path: '/api/resources-debug'
      fullPath: '/api/resources-debug'
      preLoaderRoute: typeof ApiResourcesDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resource-download': {
      id: '/api/resource-download'
      path: '/api/resource-download'
      fullPath: '/api/resource-download'
      preLoaderRoute: typeof ApiResourceDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mn-webhook': {
      id: '/api/mn-webhook'
      path: '/api/mn-webhook'
      fullPath: '/api/mn-webhook'
      preLoaderRoute: typeof ApiMnWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-summary': {
      id: '/api/generate-summary'
      path: '/api/generate-summary'
      fullPath: '/api/generate-summary'
      preLoaderRoute: typeof ApiGenerateSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demons': {
      id: '/api/demons'
      path: '/api/demons'
      fullPath: '/api/demons'
      preLoaderRoute: typeof ApiDemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment-board': {
      id: '/api/assessment-board'
      path: '/api/assessment-board'
      fullPath: '/api/assessment-board'
      preLoaderRoute: typeof ApiAssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  AssessmentBoardRoute: AssessmentBoardRoute,
  ResourcesRoute: ResourcesRoute,
  SubmitDemonRoute: SubmitDemonRoute,
  ApiAssessmentBoardRoute: ApiAssessmentBoardRoute,
  ApiDemonsRoute: ApiDemonsRoute,
  ApiGenerateSummaryRoute: ApiGenerateSummaryRoute,
  ApiMnWebhookRoute: ApiMnWebhookRoute,
  ApiResourceDownloadRoute: ApiResourceDownloadRoute,
  ApiResourcesRoute: ApiResourcesRoute,
  ApiResourcesDebugRoute: ApiResourcesDebugRoute,
  ApiSubmitAssessmentRoute: ApiSubmitAssessmentRoute,
  ApiWarroomChatRoute: ApiWarroomChatRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
