/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitDemonRouteImport } from './routes/submit-demon'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AssessmentBoardRouteImport } from './routes/assessment-board'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ArsenalRouteImport } from './routes/arsenal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiWarroomChatRouteImport } from './routes/api.warroom-chat'
import { Route as ApiUserTierRouteImport } from './routes/api.user-tier'
import { Route as ApiUpdateProfileRouteImport } from './routes/api.update-profile'
import { Route as ApiSubmitHelpRouteImport } from './routes/api.submit-help'
import { Route as ApiSubmitAssessmentRouteImport } from './routes/api.submit-assessment'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as ApiStreamTokenRouteImport } from './routes/api.stream-token'
import { Route as ApiResourcesDebugRouteImport } from './routes/api.resources-debug'
import { Route as ApiResourcesRouteImport } from './routes/api.resources'
import { Route as ApiResourceDownloadRouteImport } from './routes/api.resource-download'
import { Route as ApiMnVerifyRouteImport } from './routes/api.mn-verify'
import { Route as ApiGetMembersRouteImport } from './routes/api.get-members'
import { Route as ApiGenerateSummaryRouteImport } from './routes/api.generate-summary'
import { Route as ApiGenerateFieldCardRouteImport } from './routes/api.generate-field-card'
import { Route as ApiDemonsRouteImport } from './routes/api.demons'
import { Route as ApiClerkWebhookRouteImport } from './routes/api.clerk-webhook'
import { Route as ApiAssessmentBoardRouteImport } from './routes/api.assessment-board'
import { Route as ApiAdminUploadRouteImport } from './routes/api.admin-upload'
import { Route as ApiAdminAuthRouteImport } from './routes/api.admin-auth'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const SubmitDemonRoute = SubmitDemonRouteImport.update({
  id: '/submit-demon',
  path: '/submit-demon',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBoardRoute = AssessmentBoardRouteImport.update({
  id: '/assessment-board',
  path: '/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsenalRoute = ArsenalRouteImport.update({
  id: '/arsenal',
  path: '/arsenal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarroomChatRoute = ApiWarroomChatRouteImport.update({
  id: '/api/warroom-chat',
  path: '/api/warroom-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserTierRoute = ApiUserTierRouteImport.update({
  id: '/api/user-tier',
  path: '/api/user-tier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateProfileRoute = ApiUpdateProfileRouteImport.update({
  id: '/api/update-profile',
  path: '/api/update-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitHelpRoute = ApiSubmitHelpRouteImport.update({
  id: '/api/submit-help',
  path: '/api/submit-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitAssessmentRoute = ApiSubmitAssessmentRouteImport.update({
  id: '/api/submit-assessment',
  path: '/api/submit-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamTokenRoute = ApiStreamTokenRouteImport.update({
  id: '/api/stream-token',
  path: '/api/stream-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesDebugRoute = ApiResourcesDebugRouteImport.update({
  id: '/api/resources-debug',
  path: '/api/resources-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceDownloadRoute = ApiResourceDownloadRouteImport.update({
  id: '/api/resource-download',
  path: '/api/resource-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMnVerifyRoute = ApiMnVerifyRouteImport.update({
  id: '/api/mn-verify',
  path: '/api/mn-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetMembersRoute = ApiGetMembersRouteImport.update({
  id: '/api/get-members',
  path: '/api/get-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSummaryRoute = ApiGenerateSummaryRouteImport.update({
  id: '/api/generate-summary',
  path: '/api/generate-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateFieldCardRoute = ApiGenerateFieldCardRouteImport.update({
  id: '/api/generate-field-card',
  path: '/api/generate-field-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemonsRoute = ApiDemonsRouteImport.update({
  id: '/api/demons',
  path: '/api/demons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClerkWebhookRoute = ApiClerkWebhookRouteImport.update({
  id: '/api/clerk-webhook',
  path: '/api/clerk-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentBoardRoute = ApiAssessmentBoardRouteImport.update({
  id: '/api/assessment-board',
  path: '/api/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin-upload',
  path: '/api/admin-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin-auth',
  path: '/api/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arsenal': typeof ArsenalRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/community': typeof CommunityRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/admin-upload': typeof ApiAdminUploadRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-field-card': typeof ApiGenerateFieldCardRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/get-members': typeof ApiGetMembersRoute
  '/api/mn-verify': typeof ApiMnVerifyRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/stream-token': typeof ApiStreamTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/submit-help': typeof ApiSubmitHelpRoute
  '/api/update-profile': typeof ApiUpdateProfileRoute
  '/api/user-tier': typeof ApiUserTierRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arsenal': typeof ArsenalRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/community': typeof CommunityRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/admin-upload': typeof ApiAdminUploadRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-field-card': typeof ApiGenerateFieldCardRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/get-members': typeof ApiGetMembersRoute
  '/api/mn-verify': typeof ApiMnVerifyRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/stream-token': typeof ApiStreamTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/submit-help': typeof ApiSubmitHelpRoute
  '/api/update-profile': typeof ApiUpdateProfileRoute
  '/api/user-tier': typeof ApiUserTierRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arsenal': typeof ArsenalRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/community': typeof CommunityRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/admin-upload': typeof ApiAdminUploadRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-field-card': typeof ApiGenerateFieldCardRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/get-members': typeof ApiGetMembersRoute
  '/api/mn-verify': typeof ApiMnVerifyRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/stream-token': typeof ApiStreamTokenRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/submit-help': typeof ApiSubmitHelpRoute
  '/api/update-profile': typeof ApiUpdateProfileRoute
  '/api/user-tier': typeof ApiUserTierRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arsenal'
    | '/assessment'
    | '/assessment-board'
    | '/community'
    | '/help'
    | '/join'
    | '/membership'
    | '/sign-in'
    | '/sign-up'
    | '/submit-demon'
    | '/admin/login'
    | '/api/admin-auth'
    | '/api/admin-upload'
    | '/api/assessment-board'
    | '/api/clerk-webhook'
    | '/api/demons'
    | '/api/generate-field-card'
    | '/api/generate-summary'
    | '/api/get-members'
    | '/api/mn-verify'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/stream-token'
    | '/api/stripe-webhook'
    | '/api/submit-assessment'
    | '/api/submit-help'
    | '/api/update-profile'
    | '/api/user-tier'
    | '/api/warroom-chat'
    | '/products/$productId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arsenal'
    | '/assessment'
    | '/assessment-board'
    | '/community'
    | '/help'
    | '/join'
    | '/membership'
    | '/sign-in'
    | '/sign-up'
    | '/submit-demon'
    | '/admin/login'
    | '/api/admin-auth'
    | '/api/admin-upload'
    | '/api/assessment-board'
    | '/api/clerk-webhook'
    | '/api/demons'
    | '/api/generate-field-card'
    | '/api/generate-summary'
    | '/api/get-members'
    | '/api/mn-verify'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/stream-token'
    | '/api/stripe-webhook'
    | '/api/submit-assessment'
    | '/api/submit-help'
    | '/api/update-profile'
    | '/api/user-tier'
    | '/api/warroom-chat'
    | '/products/$productId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/arsenal'
    | '/assessment'
    | '/assessment-board'
    | '/community'
    | '/help'
    | '/join'
    | '/membership'
    | '/sign-in'
    | '/sign-up'
    | '/submit-demon'
    | '/admin/login'
    | '/api/admin-auth'
    | '/api/admin-upload'
    | '/api/assessment-board'
    | '/api/clerk-webhook'
    | '/api/demons'
    | '/api/generate-field-card'
    | '/api/generate-summary'
    | '/api/get-members'
    | '/api/mn-verify'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/stream-token'
    | '/api/stripe-webhook'
    | '/api/submit-assessment'
    | '/api/submit-help'
    | '/api/update-profile'
    | '/api/user-tier'
    | '/api/warroom-chat'
    | '/products/$productId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArsenalRoute: typeof ArsenalRoute
  AssessmentRoute: typeof AssessmentRoute
  AssessmentBoardRoute: typeof AssessmentBoardRoute
  CommunityRoute: typeof CommunityRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  MembershipRoute: typeof MembershipRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SubmitDemonRoute: typeof SubmitDemonRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiAssessmentBoardRoute: typeof ApiAssessmentBoardRoute
  ApiClerkWebhookRoute: typeof ApiClerkWebhookRoute
  ApiDemonsRoute: typeof ApiDemonsRoute
  ApiGenerateFieldCardRoute: typeof ApiGenerateFieldCardRoute
  ApiGenerateSummaryRoute: typeof ApiGenerateSummaryRoute
  ApiGetMembersRoute: typeof ApiGetMembersRoute
  ApiMnVerifyRoute: typeof ApiMnVerifyRoute
  ApiResourceDownloadRoute: typeof ApiResourceDownloadRoute
  ApiResourcesRoute: typeof ApiResourcesRoute
  ApiResourcesDebugRoute: typeof ApiResourcesDebugRoute
  ApiStreamTokenRoute: typeof ApiStreamTokenRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiSubmitAssessmentRoute: typeof ApiSubmitAssessmentRoute
  ApiSubmitHelpRoute: typeof ApiSubmitHelpRoute
  ApiUpdateProfileRoute: typeof ApiUpdateProfileRoute
  ApiUserTierRoute: typeof ApiUserTierRoute
  ApiWarroomChatRoute: typeof ApiWarroomChatRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-demon': {
      id: '/submit-demon'
      path: '/submit-demon'
      fullPath: '/submit-demon'
      preLoaderRoute: typeof SubmitDemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment-board': {
      id: '/assessment-board'
      path: '/assessment-board'
      fullPath: '/assessment-board'
      preLoaderRoute: typeof AssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsenal': {
      id: '/arsenal'
      path: '/arsenal'
      fullPath: '/arsenal'
      preLoaderRoute: typeof ArsenalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warroom-chat': {
      id: '/api/warroom-chat'
      path: '/api/warroom-chat'
      fullPath: '/api/warroom-chat'
      preLoaderRoute: typeof ApiWarroomChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-tier': {
      id: '/api/user-tier'
      path: '/api/user-tier'
      fullPath: '/api/user-tier'
      preLoaderRoute: typeof ApiUserTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-profile': {
      id: '/api/update-profile'
      path: '/api/update-profile'
      fullPath: '/api/update-profile'
      preLoaderRoute: typeof ApiUpdateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-help': {
      id: '/api/submit-help'
      path: '/api/submit-help'
      fullPath: '/api/submit-help'
      preLoaderRoute: typeof ApiSubmitHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-assessment': {
      id: '/api/submit-assessment'
      path: '/api/submit-assessment'
      fullPath: '/api/submit-assessment'
      preLoaderRoute: typeof ApiSubmitAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-token': {
      id: '/api/stream-token'
      path: '/api/stream-token'
      fullPath: '/api/stream-token'
      preLoaderRoute: typeof ApiStreamTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources-debug': {
      id: '/api/resources-debug'
      path: '/api/resources-debug'
      fullPath: '/api/resources-debug'
      preLoaderRoute: typeof ApiResourcesDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resource-download': {
      id: '/api/resource-download'
      path: '/api/resource-download'
      fullPath: '/api/resource-download'
      preLoaderRoute: typeof ApiResourceDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mn-verify': {
      id: '/api/mn-verify'
      path: '/api/mn-verify'
      fullPath: '/api/mn-verify'
      preLoaderRoute: typeof ApiMnVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-members': {
      id: '/api/get-members'
      path: '/api/get-members'
      fullPath: '/api/get-members'
      preLoaderRoute: typeof ApiGetMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-summary': {
      id: '/api/generate-summary'
      path: '/api/generate-summary'
      fullPath: '/api/generate-summary'
      preLoaderRoute: typeof ApiGenerateSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-field-card': {
      id: '/api/generate-field-card'
      path: '/api/generate-field-card'
      fullPath: '/api/generate-field-card'
      preLoaderRoute: typeof ApiGenerateFieldCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demons': {
      id: '/api/demons'
      path: '/api/demons'
      fullPath: '/api/demons'
      preLoaderRoute: typeof ApiDemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clerk-webhook': {
      id: '/api/clerk-webhook'
      path: '/api/clerk-webhook'
      fullPath: '/api/clerk-webhook'
      preLoaderRoute: typeof ApiClerkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment-board': {
      id: '/api/assessment-board'
      path: '/api/assessment-board'
      fullPath: '/api/assessment-board'
      preLoaderRoute: typeof ApiAssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-upload': {
      id: '/api/admin-upload'
      path: '/api/admin-upload'
      fullPath: '/api/admin-upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-auth': {
      id: '/api/admin-auth'
      path: '/api/admin-auth'
      fullPath: '/api/admin-auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArsenalRoute: ArsenalRoute,
  AssessmentRoute: AssessmentRoute,
  AssessmentBoardRoute: AssessmentBoardRoute,
  CommunityRoute: CommunityRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  MembershipRoute: MembershipRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SubmitDemonRoute: SubmitDemonRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiAssessmentBoardRoute: ApiAssessmentBoardRoute,
  ApiClerkWebhookRoute: ApiClerkWebhookRoute,
  ApiDemonsRoute: ApiDemonsRoute,
  ApiGenerateFieldCardRoute: ApiGenerateFieldCardRoute,
  ApiGenerateSummaryRoute: ApiGenerateSummaryRoute,
  ApiGetMembersRoute: ApiGetMembersRoute,
  ApiMnVerifyRoute: ApiMnVerifyRoute,
  ApiResourceDownloadRoute: ApiResourceDownloadRoute,
  ApiResourcesRoute: ApiResourcesRoute,
  ApiResourcesDebugRoute: ApiResourcesDebugRoute,
  ApiStreamTokenRoute: ApiStreamTokenRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiSubmitAssessmentRoute: ApiSubmitAssessmentRoute,
  ApiSubmitHelpRoute: ApiSubmitHelpRoute,
  ApiUpdateProfileRoute: ApiUpdateProfileRoute,
  ApiUserTierRoute: ApiUserTierRoute,
  ApiWarroomChatRoute: ApiWarroomChatRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
