/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitDemonRouteImport } from './routes/submit-demon'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InvestigateRouteImport } from './routes/investigate'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AssessmentBoardRouteImport } from './routes/assessment-board'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as ArsenalRouteImport } from './routes/arsenal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as CommunitySpiritualMappingRouteImport } from './routes/community_.spiritual-mapping'
import { Route as CommunitySearchRouteImport } from './routes/community_.search'
import { Route as CommunitySpiritsSpiriIdRouteImport } from './routes/community_.spirits.$spiritId'
import { Route as CommunityScriptureRouteImport } from './routes/community_.scripture'
import { Route as CommunityQrfRouteImport } from './routes/community_.qrf'
import { Route as CommunityForumRouteImport } from './routes/community_.forum'
import { Route as CommunityFieldOpsRouteImport } from './routes/community_.field-ops'
import { Route as CommunityFieldManualRouteImport } from './routes/community_.field-manual'
import { Route as CommunityDreamInterpreterRouteImport } from './routes/community_.dream-interpreter'
import { Route as CommunityAskSolRouteImport } from './routes/community_.ask-sol'
import { Route as ApiWarroomChatRouteImport } from './routes/api.warroom-chat'
import { Route as ApiUserTierRouteImport } from './routes/api.user-tier'
import { Route as ApiUpdateProfileRouteImport } from './routes/api.update-profile'
import { Route as ApiSubmitHelpRouteImport } from './routes/api.submit-help'
import { Route as ApiSubmitAssessmentRouteImport } from './routes/api.submit-assessment'
import { Route as ApiSmSubmissionRouteImport } from './routes/api.sm-submission'
import { Route as ApiSmRegionsRouteImport } from './routes/api.sm-regions'
import { Route as ApiSmAssessmentRouteImport } from './routes/api.sm-assessment'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApiResourcesDebugRouteImport } from './routes/api.resources-debug'
import { Route as ApiResourcesRouteImport } from './routes/api.resources'
import { Route as ApiResourceDownloadRouteImport } from './routes/api.resource-download'
import { Route as ApiMnVerifyRouteImport } from './routes/api.mn-verify'
import { Route as ApiGetMembersRouteImport } from './routes/api.get-members'
import { Route as ApiGenerateSummaryRouteImport } from './routes/api.generate-summary'
import { Route as ApiGenerateFieldCardRouteImport } from './routes/api.generate-field-card'
import { Route as ApiDemonsRouteImport } from './routes/api.demons'
import { Route as ApiClerkWebhookRouteImport } from './routes/api.clerk-webhook'
import { Route as ApiAssessmentBoardRouteImport } from './routes/api.assessment-board'
import { Route as ApiAdminUploadRouteImport } from './routes/api.admin-upload'
import { Route as ApiAdminAuthRouteImport } from './routes/api.admin-auth'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminChurchFathersLibraryRouteImport } from './routes/admin.church-fathers-library'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitDemonRoute = SubmitDemonRouteImport.update({
  id: '/submit-demon',
  path: '/submit-demon',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateRoute = InvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentBoardRoute = AssessmentBoardRouteImport.update({
  id: '/assessment-board',
  path: '/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsenalRoute = ArsenalRouteImport.update({
  id: '/arsenal',
  path: '/arsenal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySpiritualMappingRoute =
  CommunitySpiritualMappingRouteImport.update({
    id: '/community_/spiritual-mapping',
    path: '/community/spiritual-mapping',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunitySearchRoute = CommunitySearchRouteImport.update({
  id: '/community_/search',
  path: '/community/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySpiritsSpiriIdRoute = CommunitySpiritsSpiriIdRouteImport.update({
  id: '/community_/spirits/$spiritId',
  path: '/community/spirits/$spiritId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityScriptureRoute = CommunityScriptureRouteImport.update({
  id: '/community_/scripture',
  path: '/community/scripture',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityQrfRoute = CommunityQrfRouteImport.update({
  id: '/community_/qrf',
  path: '/community/qrf',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityForumRoute = CommunityForumRouteImport.update({
  id: '/community_/forum',
  path: '/community/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFieldOpsRoute = CommunityFieldOpsRouteImport.update({
  id: '/community_/field-ops',
  path: '/community/field-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFieldManualRoute = CommunityFieldManualRouteImport.update({
  id: '/community_/field-manual',
  path: '/community/field-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityDreamInterpreterRoute =
  CommunityDreamInterpreterRouteImport.update({
    id: '/community_/dream-interpreter',
    path: '/community/dream-interpreter',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunityAskSolRoute = CommunityAskSolRouteImport.update({
  id: '/community_/ask-sol',
  path: '/community/ask-sol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarroomChatRoute = ApiWarroomChatRouteImport.update({
  id: '/api/warroom-chat',
  path: '/api/warroom-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserTierRoute = ApiUserTierRouteImport.update({
  id: '/api/user-tier',
  path: '/api/user-tier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpdateProfileRoute = ApiUpdateProfileRouteImport.update({
  id: '/api/update-profile',
  path: '/api/update-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitHelpRoute = ApiSubmitHelpRouteImport.update({
  id: '/api/submit-help',
  path: '/api/submit-help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitAssessmentRoute = ApiSubmitAssessmentRouteImport.update({
  id: '/api/submit-assessment',
  path: '/api/submit-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmSubmissionRoute = ApiSmSubmissionRouteImport.update({
  id: '/api/sm-submission',
  path: '/api/sm-submission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmRegionsRoute = ApiSmRegionsRouteImport.update({
  id: '/api/sm-regions',
  path: '/api/sm-regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmAssessmentRoute = ApiSmAssessmentRouteImport.update({
  id: '/api/sm-assessment',
  path: '/api/sm-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesDebugRoute = ApiResourcesDebugRouteImport.update({
  id: '/api/resources-debug',
  path: '/api/resources-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourceDownloadRoute = ApiResourceDownloadRouteImport.update({
  id: '/api/resource-download',
  path: '/api/resource-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMnVerifyRoute = ApiMnVerifyRouteImport.update({
  id: '/api/mn-verify',
  path: '/api/mn-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetMembersRoute = ApiGetMembersRouteImport.update({
  id: '/api/get-members',
  path: '/api/get-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSummaryRoute = ApiGenerateSummaryRouteImport.update({
  id: '/api/generate-summary',
  path: '/api/generate-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateFieldCardRoute = ApiGenerateFieldCardRouteImport.update({
  id: '/api/generate-field-card',
  path: '/api/generate-field-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemonsRoute = ApiDemonsRouteImport.update({
  id: '/api/demons',
  path: '/api/demons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClerkWebhookRoute = ApiClerkWebhookRouteImport.update({
  id: '/api/clerk-webhook',
  path: '/api/clerk-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentBoardRoute = ApiAssessmentBoardRouteImport.update({
  id: '/api/assessment-board',
  path: '/api/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin-upload',
  path: '/api/admin-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthRoute = ApiAdminAuthRouteImport.update({
  id: '/api/admin-auth',
  path: '/api/admin-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChurchFathersLibraryRoute =
  AdminChurchFathersLibraryRouteImport.update({
    id: '/church-fathers-library',
    path: '/church-fathers-library',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/arsenal': typeof ArsenalRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/community': typeof CommunityRoute
  '/donate': typeof DonateRoute
  '/help': typeof HelpRoute
  '/investigate': typeof InvestigateRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/terms': typeof TermsRoute
  '/admin/church-fathers-library': typeof AdminChurchFathersLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/admin-upload': typeof ApiAdminUploadRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-field-card': typeof ApiGenerateFieldCardRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/get-members': typeof ApiGetMembersRoute
  '/api/mn-verify': typeof ApiMnVerifyRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sm-assessment': typeof ApiSmAssessmentRoute
  '/api/sm-regions': typeof ApiSmRegionsRoute
  '/api/sm-submission': typeof ApiSmSubmissionRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/submit-help': typeof ApiSubmitHelpRoute
  '/api/update-profile': typeof ApiUpdateProfileRoute
  '/api/user-tier': typeof ApiUserTierRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/community/ask-sol': typeof CommunityAskSolRoute
  '/community/dream-interpreter': typeof CommunityDreamInterpreterRoute
  '/community/field-manual': typeof CommunityFieldManualRoute
  '/community/field-ops': typeof CommunityFieldOpsRoute
  '/community/forum': typeof CommunityForumRoute
  '/community/qrf': typeof CommunityQrfRoute
  '/community/scripture': typeof CommunityScriptureRoute
  '/community/search': typeof CommunitySearchRoute
  '/community/spiritual-mapping': typeof CommunitySpiritualMappingRoute
  '/community/spirits/$spiritId': typeof CommunitySpiritsSpiriIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/arsenal': typeof ArsenalRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/community': typeof CommunityRoute
  '/donate': typeof DonateRoute
  '/help': typeof HelpRoute
  '/investigate': typeof InvestigateRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/terms': typeof TermsRoute
  '/admin/church-fathers-library': typeof AdminChurchFathersLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/admin-upload': typeof ApiAdminUploadRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-field-card': typeof ApiGenerateFieldCardRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/get-members': typeof ApiGetMembersRoute
  '/api/mn-verify': typeof ApiMnVerifyRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sm-assessment': typeof ApiSmAssessmentRoute
  '/api/sm-regions': typeof ApiSmRegionsRoute
  '/api/sm-submission': typeof ApiSmSubmissionRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/submit-help': typeof ApiSubmitHelpRoute
  '/api/update-profile': typeof ApiUpdateProfileRoute
  '/api/user-tier': typeof ApiUserTierRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/community/ask-sol': typeof CommunityAskSolRoute
  '/community/dream-interpreter': typeof CommunityDreamInterpreterRoute
  '/community/field-manual': typeof CommunityFieldManualRoute
  '/community/field-ops': typeof CommunityFieldOpsRoute
  '/community/forum': typeof CommunityForumRoute
  '/community/qrf': typeof CommunityQrfRoute
  '/community/scripture': typeof CommunityScriptureRoute
  '/community/search': typeof CommunitySearchRoute
  '/community/spiritual-mapping': typeof CommunitySpiritualMappingRoute
  '/community/spirits/$spiritId': typeof CommunitySpiritsSpiriIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/arsenal': typeof ArsenalRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/community': typeof CommunityRoute
  '/donate': typeof DonateRoute
  '/help': typeof HelpRoute
  '/investigate': typeof InvestigateRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/submit-demon': typeof SubmitDemonRoute
  '/terms': typeof TermsRoute
  '/admin/church-fathers-library': typeof AdminChurchFathersLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/admin-auth': typeof ApiAdminAuthRoute
  '/api/admin-upload': typeof ApiAdminUploadRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/clerk-webhook': typeof ApiClerkWebhookRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-field-card': typeof ApiGenerateFieldCardRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/get-members': typeof ApiGetMembersRoute
  '/api/mn-verify': typeof ApiMnVerifyRoute
  '/api/resource-download': typeof ApiResourceDownloadRoute
  '/api/resources': typeof ApiResourcesRoute
  '/api/resources-debug': typeof ApiResourcesDebugRoute
  '/api/search': typeof ApiSearchRoute
  '/api/sm-assessment': typeof ApiSmAssessmentRoute
  '/api/sm-regions': typeof ApiSmRegionsRoute
  '/api/sm-submission': typeof ApiSmSubmissionRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/submit-help': typeof ApiSubmitHelpRoute
  '/api/update-profile': typeof ApiUpdateProfileRoute
  '/api/user-tier': typeof ApiUserTierRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/community_/ask-sol': typeof CommunityAskSolRoute
  '/community_/dream-interpreter': typeof CommunityDreamInterpreterRoute
  '/community_/field-manual': typeof CommunityFieldManualRoute
  '/community_/field-ops': typeof CommunityFieldOpsRoute
  '/community_/forum': typeof CommunityForumRoute
  '/community_/qrf': typeof CommunityQrfRoute
  '/community_/scripture': typeof CommunityScriptureRoute
  '/community_/search': typeof CommunitySearchRoute
  '/community_/spiritual-mapping': typeof CommunitySpiritualMappingRoute
  '/community_/spirits/$spiritId': typeof CommunitySpiritsSpiriIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/arsenal'
    | '/assessment'
    | '/assessment-board'
    | '/community'
    | '/donate'
    | '/help'
    | '/investigate'
    | '/join'
    | '/membership'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/submit-demon'
    | '/terms'
    | '/admin/church-fathers-library'
    | '/admin/login'
    | '/api/admin-auth'
    | '/api/admin-upload'
    | '/api/assessment-board'
    | '/api/clerk-webhook'
    | '/api/demons'
    | '/api/generate-field-card'
    | '/api/generate-summary'
    | '/api/get-members'
    | '/api/mn-verify'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/search'
    | '/api/sm-assessment'
    | '/api/sm-regions'
    | '/api/sm-submission'
    | '/api/submit-assessment'
    | '/api/submit-help'
    | '/api/update-profile'
    | '/api/user-tier'
    | '/api/warroom-chat'
    | '/community/ask-sol'
    | '/community/dream-interpreter'
    | '/community/field-manual'
    | '/community/field-ops'
    | '/community/forum'
    | '/community/qrf'
    | '/community/scripture'
    | '/community/search'
    | '/community/spiritual-mapping'
    | '/community/spirits/$spiritId'
    | '/products/$productId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/arsenal'
    | '/assessment'
    | '/assessment-board'
    | '/community'
    | '/donate'
    | '/help'
    | '/investigate'
    | '/join'
    | '/membership'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/submit-demon'
    | '/terms'
    | '/admin/church-fathers-library'
    | '/admin/login'
    | '/api/admin-auth'
    | '/api/admin-upload'
    | '/api/assessment-board'
    | '/api/clerk-webhook'
    | '/api/demons'
    | '/api/generate-field-card'
    | '/api/generate-summary'
    | '/api/get-members'
    | '/api/mn-verify'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/search'
    | '/api/sm-assessment'
    | '/api/sm-regions'
    | '/api/sm-submission'
    | '/api/submit-assessment'
    | '/api/submit-help'
    | '/api/update-profile'
    | '/api/user-tier'
    | '/api/warroom-chat'
    | '/community/ask-sol'
    | '/community/dream-interpreter'
    | '/community/field-manual'
    | '/community/field-ops'
    | '/community/forum'
    | '/community/qrf'
    | '/community/scripture'
    | '/community/search'
    | '/community/spiritual-mapping'
    | '/community/spirits/$spiritId'
    | '/products/$productId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/arsenal'
    | '/assessment'
    | '/assessment-board'
    | '/community'
    | '/donate'
    | '/help'
    | '/investigate'
    | '/join'
    | '/membership'
    | '/pricing'
    | '/privacy'
    | '/sign-in'
    | '/sign-up'
    | '/submit-demon'
    | '/terms'
    | '/admin/church-fathers-library'
    | '/admin/login'
    | '/api/admin-auth'
    | '/api/admin-upload'
    | '/api/assessment-board'
    | '/api/clerk-webhook'
    | '/api/demons'
    | '/api/generate-field-card'
    | '/api/generate-summary'
    | '/api/get-members'
    | '/api/mn-verify'
    | '/api/resource-download'
    | '/api/resources'
    | '/api/resources-debug'
    | '/api/search'
    | '/api/sm-assessment'
    | '/api/sm-regions'
    | '/api/sm-submission'
    | '/api/submit-assessment'
    | '/api/submit-help'
    | '/api/update-profile'
    | '/api/user-tier'
    | '/api/warroom-chat'
    | '/community_/ask-sol'
    | '/community_/dream-interpreter'
    | '/community_/field-manual'
    | '/community_/field-ops'
    | '/community_/forum'
    | '/community_/qrf'
    | '/community_/scripture'
    | '/community_/search'
    | '/community_/spiritual-mapping'
    | '/community_/spirits/$spiritId'
    | '/products/$productId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArsenalRoute: typeof ArsenalRoute
  AssessmentRoute: typeof AssessmentRoute
  AssessmentBoardRoute: typeof AssessmentBoardRoute
  CommunityRoute: typeof CommunityRoute
  DonateRoute: typeof DonateRoute
  HelpRoute: typeof HelpRoute
  InvestigateRoute: typeof InvestigateRoute
  JoinRoute: typeof JoinRoute
  MembershipRoute: typeof MembershipRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SubmitDemonRoute: typeof SubmitDemonRoute
  TermsRoute: typeof TermsRoute
  ApiAdminAuthRoute: typeof ApiAdminAuthRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiAssessmentBoardRoute: typeof ApiAssessmentBoardRoute
  ApiClerkWebhookRoute: typeof ApiClerkWebhookRoute
  ApiDemonsRoute: typeof ApiDemonsRoute
  ApiGenerateFieldCardRoute: typeof ApiGenerateFieldCardRoute
  ApiGenerateSummaryRoute: typeof ApiGenerateSummaryRoute
  ApiGetMembersRoute: typeof ApiGetMembersRoute
  ApiMnVerifyRoute: typeof ApiMnVerifyRoute
  ApiResourceDownloadRoute: typeof ApiResourceDownloadRoute
  ApiResourcesRoute: typeof ApiResourcesRoute
  ApiResourcesDebugRoute: typeof ApiResourcesDebugRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSmAssessmentRoute: typeof ApiSmAssessmentRoute
  ApiSmRegionsRoute: typeof ApiSmRegionsRoute
  ApiSmSubmissionRoute: typeof ApiSmSubmissionRoute
  ApiSubmitAssessmentRoute: typeof ApiSubmitAssessmentRoute
  ApiSubmitHelpRoute: typeof ApiSubmitHelpRoute
  ApiUpdateProfileRoute: typeof ApiUpdateProfileRoute
  ApiUserTierRoute: typeof ApiUserTierRoute
  ApiWarroomChatRoute: typeof ApiWarroomChatRoute
  CommunityAskSolRoute: typeof CommunityAskSolRoute
  CommunityDreamInterpreterRoute: typeof CommunityDreamInterpreterRoute
  CommunityFieldManualRoute: typeof CommunityFieldManualRoute
  CommunityFieldOpsRoute: typeof CommunityFieldOpsRoute
  CommunityForumRoute: typeof CommunityForumRoute
  CommunityQrfRoute: typeof CommunityQrfRoute
  CommunityScriptureRoute: typeof CommunityScriptureRoute
  CommunitySearchRoute: typeof CommunitySearchRoute
  CommunitySpiritualMappingRoute: typeof CommunitySpiritualMappingRoute
  CommunitySpiritsSpiriIdRoute: typeof CommunitySpiritsSpiriIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-demon': {
      id: '/submit-demon'
      path: '/submit-demon'
      fullPath: '/submit-demon'
      preLoaderRoute: typeof SubmitDemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate': {
      id: '/investigate'
      path: '/investigate'
      fullPath: '/investigate'
      preLoaderRoute: typeof InvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment-board': {
      id: '/assessment-board'
      path: '/assessment-board'
      fullPath: '/assessment-board'
      preLoaderRoute: typeof AssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsenal': {
      id: '/arsenal'
      path: '/arsenal'
      fullPath: '/arsenal'
      preLoaderRoute: typeof ArsenalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/spiritual-mapping': {
      id: '/community_/spiritual-mapping'
      path: '/community/spiritual-mapping'
      fullPath: '/community/spiritual-mapping'
      preLoaderRoute: typeof CommunitySpiritualMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/search': {
      id: '/community_/search'
      path: '/community/search'
      fullPath: '/community/search'
      preLoaderRoute: typeof CommunitySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/spirits/$spiritId': {
      id: '/community_/spirits/$spiritId'
      path: '/community/spirits/$spiritId'
      fullPath: '/community/spirits/$spiritId'
      preLoaderRoute: typeof CommunitySpiritsSpiriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/scripture': {
      id: '/community_/scripture'
      path: '/community/scripture'
      fullPath: '/community/scripture'
      preLoaderRoute: typeof CommunityScriptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/qrf': {
      id: '/community_/qrf'
      path: '/community/qrf'
      fullPath: '/community/qrf'
      preLoaderRoute: typeof CommunityQrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/forum': {
      id: '/community_/forum'
      path: '/community/forum'
      fullPath: '/community/forum'
      preLoaderRoute: typeof CommunityForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/field-ops': {
      id: '/community_/field-ops'
      path: '/community/field-ops'
      fullPath: '/community/field-ops'
      preLoaderRoute: typeof CommunityFieldOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/field-manual': {
      id: '/community_/field-manual'
      path: '/community/field-manual'
      fullPath: '/community/field-manual'
      preLoaderRoute: typeof CommunityFieldManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/dream-interpreter': {
      id: '/community_/dream-interpreter'
      path: '/community/dream-interpreter'
      fullPath: '/community/dream-interpreter'
      preLoaderRoute: typeof CommunityDreamInterpreterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/ask-sol': {
      id: '/community_/ask-sol'
      path: '/community/ask-sol'
      fullPath: '/community/ask-sol'
      preLoaderRoute: typeof CommunityAskSolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warroom-chat': {
      id: '/api/warroom-chat'
      path: '/api/warroom-chat'
      fullPath: '/api/warroom-chat'
      preLoaderRoute: typeof ApiWarroomChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-tier': {
      id: '/api/user-tier'
      path: '/api/user-tier'
      fullPath: '/api/user-tier'
      preLoaderRoute: typeof ApiUserTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/update-profile': {
      id: '/api/update-profile'
      path: '/api/update-profile'
      fullPath: '/api/update-profile'
      preLoaderRoute: typeof ApiUpdateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-help': {
      id: '/api/submit-help'
      path: '/api/submit-help'
      fullPath: '/api/submit-help'
      preLoaderRoute: typeof ApiSubmitHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-assessment': {
      id: '/api/submit-assessment'
      path: '/api/submit-assessment'
      fullPath: '/api/submit-assessment'
      preLoaderRoute: typeof ApiSubmitAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sm-submission': {
      id: '/api/sm-submission'
      path: '/api/sm-submission'
      fullPath: '/api/sm-submission'
      preLoaderRoute: typeof ApiSmSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sm-regions': {
      id: '/api/sm-regions'
      path: '/api/sm-regions'
      fullPath: '/api/sm-regions'
      preLoaderRoute: typeof ApiSmRegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sm-assessment': {
      id: '/api/sm-assessment'
      path: '/api/sm-assessment'
      fullPath: '/api/sm-assessment'
      preLoaderRoute: typeof ApiSmAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources-debug': {
      id: '/api/resources-debug'
      path: '/api/resources-debug'
      fullPath: '/api/resources-debug'
      preLoaderRoute: typeof ApiResourcesDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resource-download': {
      id: '/api/resource-download'
      path: '/api/resource-download'
      fullPath: '/api/resource-download'
      preLoaderRoute: typeof ApiResourceDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mn-verify': {
      id: '/api/mn-verify'
      path: '/api/mn-verify'
      fullPath: '/api/mn-verify'
      preLoaderRoute: typeof ApiMnVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-members': {
      id: '/api/get-members'
      path: '/api/get-members'
      fullPath: '/api/get-members'
      preLoaderRoute: typeof ApiGetMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-summary': {
      id: '/api/generate-summary'
      path: '/api/generate-summary'
      fullPath: '/api/generate-summary'
      preLoaderRoute: typeof ApiGenerateSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-field-card': {
      id: '/api/generate-field-card'
      path: '/api/generate-field-card'
      fullPath: '/api/generate-field-card'
      preLoaderRoute: typeof ApiGenerateFieldCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demons': {
      id: '/api/demons'
      path: '/api/demons'
      fullPath: '/api/demons'
      preLoaderRoute: typeof ApiDemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clerk-webhook': {
      id: '/api/clerk-webhook'
      path: '/api/clerk-webhook'
      fullPath: '/api/clerk-webhook'
      preLoaderRoute: typeof ApiClerkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment-board': {
      id: '/api/assessment-board'
      path: '/api/assessment-board'
      fullPath: '/api/assessment-board'
      preLoaderRoute: typeof ApiAssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-upload': {
      id: '/api/admin-upload'
      path: '/api/admin-upload'
      fullPath: '/api/admin-upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-auth': {
      id: '/api/admin-auth'
      path: '/api/admin-auth'
      fullPath: '/api/admin-auth'
      preLoaderRoute: typeof ApiAdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/church-fathers-library': {
      id: '/admin/church-fathers-library'
      path: '/church-fathers-library'
      fullPath: '/admin/church-fathers-library'
      preLoaderRoute: typeof AdminChurchFathersLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChurchFathersLibraryRoute: typeof AdminChurchFathersLibraryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChurchFathersLibraryRoute: AdminChurchFathersLibraryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  ArsenalRoute: ArsenalRoute,
  AssessmentRoute: AssessmentRoute,
  AssessmentBoardRoute: AssessmentBoardRoute,
  CommunityRoute: CommunityRoute,
  DonateRoute: DonateRoute,
  HelpRoute: HelpRoute,
  InvestigateRoute: InvestigateRoute,
  JoinRoute: JoinRoute,
  MembershipRoute: MembershipRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SubmitDemonRoute: SubmitDemonRoute,
  TermsRoute: TermsRoute,
  ApiAdminAuthRoute: ApiAdminAuthRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiAssessmentBoardRoute: ApiAssessmentBoardRoute,
  ApiClerkWebhookRoute: ApiClerkWebhookRoute,
  ApiDemonsRoute: ApiDemonsRoute,
  ApiGenerateFieldCardRoute: ApiGenerateFieldCardRoute,
  ApiGenerateSummaryRoute: ApiGenerateSummaryRoute,
  ApiGetMembersRoute: ApiGetMembersRoute,
  ApiMnVerifyRoute: ApiMnVerifyRoute,
  ApiResourceDownloadRoute: ApiResourceDownloadRoute,
  ApiResourcesRoute: ApiResourcesRoute,
  ApiResourcesDebugRoute: ApiResourcesDebugRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSmAssessmentRoute: ApiSmAssessmentRoute,
  ApiSmRegionsRoute: ApiSmRegionsRoute,
  ApiSmSubmissionRoute: ApiSmSubmissionRoute,
  ApiSubmitAssessmentRoute: ApiSubmitAssessmentRoute,
  ApiSubmitHelpRoute: ApiSubmitHelpRoute,
  ApiUpdateProfileRoute: ApiUpdateProfileRoute,
  ApiUserTierRoute: ApiUserTierRoute,
  ApiWarroomChatRoute: ApiWarroomChatRoute,
  CommunityAskSolRoute: CommunityAskSolRoute,
  CommunityDreamInterpreterRoute: CommunityDreamInterpreterRoute,
  CommunityFieldManualRoute: CommunityFieldManualRoute,
  CommunityFieldOpsRoute: CommunityFieldOpsRoute,
  CommunityForumRoute: CommunityForumRoute,
  CommunityQrfRoute: CommunityQrfRoute,
  CommunityScriptureRoute: CommunityScriptureRoute,
  CommunitySearchRoute: CommunitySearchRoute,
  CommunitySpiritualMappingRoute: CommunitySpiritualMappingRoute,
  CommunitySpiritsSpiriIdRoute: CommunitySpiritsSpiriIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
