/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AssessmentBoardRouteImport } from './routes/assessment-board'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiWarroomChatRouteImport } from './routes/api.warroom-chat'
import { Route as ApiSubmitAssessmentRouteImport } from './routes/api.submit-assessment'
import { Route as ApiGenerateSummaryRouteImport } from './routes/api.generate-summary'
import { Route as ApiDemonsRouteImport } from './routes/api.demons'
import { Route as ApiAssessmentBoardRouteImport } from './routes/api.assessment-board'

const AssessmentBoardRoute = AssessmentBoardRouteImport.update({
  id: '/assessment-board',
  path: '/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarroomChatRoute = ApiWarroomChatRouteImport.update({
  id: '/api/warroom-chat',
  path: '/api/warroom-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitAssessmentRoute = ApiSubmitAssessmentRouteImport.update({
  id: '/api/submit-assessment',
  path: '/api/submit-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSummaryRoute = ApiGenerateSummaryRouteImport.update({
  id: '/api/generate-summary',
  path: '/api/generate-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemonsRoute = ApiDemonsRouteImport.update({
  id: '/api/demons',
  path: '/api/demons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentBoardRoute = ApiAssessmentBoardRouteImport.update({
  id: '/api/assessment-board',
  path: '/api/assessment-board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/assessment-board': typeof AssessmentBoardRoute
  '/api/assessment-board': typeof ApiAssessmentBoardRoute
  '/api/demons': typeof ApiDemonsRoute
  '/api/generate-summary': typeof ApiGenerateSummaryRoute
  '/api/submit-assessment': typeof ApiSubmitAssessmentRoute
  '/api/warroom-chat': typeof ApiWarroomChatRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/assessment-board'
    | '/api/assessment-board'
    | '/api/demons'
    | '/api/generate-summary'
    | '/api/submit-assessment'
    | '/api/warroom-chat'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/assessment-board'
    | '/api/assessment-board'
    | '/api/demons'
    | '/api/generate-summary'
    | '/api/submit-assessment'
    | '/api/warroom-chat'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/assessment-board'
    | '/api/assessment-board'
    | '/api/demons'
    | '/api/generate-summary'
    | '/api/submit-assessment'
    | '/api/warroom-chat'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  AssessmentBoardRoute: typeof AssessmentBoardRoute
  ApiAssessmentBoardRoute: typeof ApiAssessmentBoardRoute
  ApiDemonsRoute: typeof ApiDemonsRoute
  ApiGenerateSummaryRoute: typeof ApiGenerateSummaryRoute
  ApiSubmitAssessmentRoute: typeof ApiSubmitAssessmentRoute
  ApiWarroomChatRoute: typeof ApiWarroomChatRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/assessment-board': {
      id: '/assessment-board'
      path: '/assessment-board'
      fullPath: '/assessment-board'
      preLoaderRoute: typeof AssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warroom-chat': {
      id: '/api/warroom-chat'
      path: '/api/warroom-chat'
      fullPath: '/api/warroom-chat'
      preLoaderRoute: typeof ApiWarroomChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-assessment': {
      id: '/api/submit-assessment'
      path: '/api/submit-assessment'
      fullPath: '/api/submit-assessment'
      preLoaderRoute: typeof ApiSubmitAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-summary': {
      id: '/api/generate-summary'
      path: '/api/generate-summary'
      fullPath: '/api/generate-summary'
      preLoaderRoute: typeof ApiGenerateSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demons': {
      id: '/api/demons'
      path: '/api/demons'
      fullPath: '/api/demons'
      preLoaderRoute: typeof ApiDemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessment-board': {
      id: '/api/assessment-board'
      path: '/api/assessment-board'
      fullPath: '/api/assessment-board'
      preLoaderRoute: typeof ApiAssessmentBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  AssessmentBoardRoute: AssessmentBoardRoute,
  ApiAssessmentBoardRoute: ApiAssessmentBoardRoute,
  ApiDemonsRoute: ApiDemonsRoute,
  ApiGenerateSummaryRoute: ApiGenerateSummaryRoute,
  ApiSubmitAssessmentRoute: ApiSubmitAssessmentRoute,
  ApiWarroomChatRoute: ApiWarroomChatRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
