ALTER TABLE events ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS attachments JSONB DEFAULT '[]';
ALTER TABLE events ADD COLUMN IF NOT EXISTS related_spirits TEXT[] DEFAULT '{}';
